# Generated by Django 5.0.6 on 2024-07-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedmovie',
            name='poster',
            field=models.CharField(default='nopathprovided', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchedmovie',
            name='title',
            field=models.CharField(default='notitleprovided', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchedmovie',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
