# Generated by Django 5.0.6 on 2024-07-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_watchedmovie_poster_watchedmovie_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedmovie',
            name='imdb_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='watchedtv',
            name='imdb_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
