# Generated by Django 5.0.6 on 2024-07-12 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_watchedmovie_imdb_id_alter_watchedtv_imdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedtv',
            name='episode',
        ),
    ]
