# Generated by Django 5.0.6 on 2024-07-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_watchedtv_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservideo',
            name='user',
        ),
        migrations.AddField(
            model_name='watchedtv',
            name='poster',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchedtv',
            name='title',
            field=models.CharField(default='notitle', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchedtv',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InProgressMovie',
        ),
        migrations.DeleteModel(
            name='UserVideo',
        ),
    ]
